# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-HTML-BBCode
version:      0.01
version_from: lib/Template/Plugin/HTML/BBCode.pm
installdirs:  site
requires:
    HTML::BBCode:                  1.01
    Template:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
